client.c File Reference
This file is used to generate a client shell, which is used to connect to the server part.
#include <errno.h>
*
#include <stdio.h>
*
#include <string.h>
*
#include <stdlib.h>
*
#include `storage.h`
*
#include <time.h>
*
#include <sys/time.h>
*
#include `utils.h`
*
#include `logger.h`
*
Macros
#define MAX_CENSUS_CITY_NUM 692
The maximum city number in census part.
Functions
void PrintValue (char *the_label)
Start a client to interact with the storage server.
int main (int argc, char *argv[])
Detailed Description
This file is used to generate a client shell, which is used to connect to the server part. The client connects to the server, running at SERVERHOST:SERVERPORT and performs a number of storage_* operations. If there are errors, the client exits.
Definition in file client.c.
Function Documentation
int main (int argc, char * argv[])
selection[0] = '\0';
Definition at line 50 of file client.c.
References Authenticated, file, MAX_CENSUS_CITY_NUM, MAX_RECORDS_PER_TABLE, MAX_STRTYPE_SIZE, MAX_VALUE_LEN, storage_record::metadata, storage_auth(), storage_connect(), storage_disconnect(), storage_get(), storage_query(), storage_set(), and storage_record::value.
void PrintValue (char * the_label)
Start a client to interact with the storage server.
If connect is successful, the client performs a storage_set/get() on TABLE and KEY and outputs the results on stdout. Finally, it exists after disconnecting from the server.
Parameters
argc The number of strings pointed to by argv
argv[] An array of pointers to characters
Returns
Return 0 when we want to exit the main function
Definition at line 45 of file client.c.