server.c File Reference
This file implements the storage server.
#include <pthread.h>
*
#include <stdio.h>
*
#include <stdlib.h>
*
#include <unistd.h>
*
#include <sys/types.h>
*
#include <sys/socket.h>
*
#include <sys/time.h>
*
#include <arpa/inet.h>
*
#include <netdb.h>
*
#include <string.h>
*
#include <assert.h>
*
#include <signal.h>
*
#include `utils.h`
*
#include <time.h>
*
#include <ctype.h>
*
#include <stdbool.h>
*
Classes
struct string
This is the declaration of the struct string, which is used for holding value data inside.
struct thread_data
Process a command from the client.
Macros
#define MAX_CONFIG_LINE_LEN 1024
Max characters in each config file line.
#define MAX_USERNAME_LEN 64
Max characters of server username.
#define MAX_ENC_PASSWORD_LEN 64
Max characters of server's encrypted password.
#define MAX_HOST_LEN 64
Max characters of server hostname.
#define MAX_PORT_LEN 8
Max characters of server port.
#define MAX_PATH_LEN 256
Max characters of data directory path.
#define MAX_TABLES 100
Max tables supported by the server.
#define MAX_RECORDS_PER_TABLE 1000
Max records per table.
#define MAX_TABLE_LEN 20
Max characters of a table name.
#define MAX_KEY_LEN 20
Max characters of a key name.
#define MAX_CONNECTIONS 10
Max simultaneous client connections.
#define MAX_COLUMNS_PER_TABLE 10
Max columns per table.
#define MAX_COLNAME_LEN 20
Max characters of a column name.
#define MAX_STRTYPE_SIZE 40
Max SIZE of string types.
#define MAX_VALUE_LEN 800
Max characters of a value.
#define MAX_LISTENQUEUELEN 20
The maximum number of queued connections.
#define LOGGING 0
#define MAX_CENSUS_CITY_NUM 693
The maximum city numbers.
Functions
bool TestingCharArray (const char *chararray)
Check whether a string is actually a valid integer.
void ModifyString3 (char *char_source)
void * handle_client (void *data)
int handle_command (FILE *file1, int sock, char *cmd, struct config_params params)
int main (int argc, char *argv[])
Start the storage server.
Variables
struct string TableOfData [MAX_TABLES][MAX_RECORDS_PER_TABLE][11]
This initialization declares a struct, which is used for holding table of data.
struct string QueryHolder [MAX_RECORDS_PER_TABLE][MAX_COLUMNS_PER_TABLE+1]
This initialization declares a struct, which is used for holding query.
struct string QueryResultHolder [MAX_RECORDS_PER_TABLE][MAX_COLUMNS_PER_TABLE+1]
This initialization declares a struct, which is used for holding the result of the query.
int long total_processing_time = 0
This initialization is for counting the total processing time.
struct thread_data thread_data_array [MAX_CONNECTIONS]
Detailed Description
This file implements the storage server. The storage server should be named `server` and should take a single command line argument that refers to the configuration file.
The storage server should be able to communicate with the client library functions declared in storage.h and implemented in storage.c.
Definition in file server.c.
Function Documentation
int main (int argc, char * argv[])
Start the storage server.
This is the main entry point for the storage server. It reads the configuration file, starts listening on a port, and proccesses commands from clients.
Parameters
argc The number of strings pointed to by argv
argv[] An array of pointers to characters
Returns
Return EXIT_SUCCESS if we can exit successfully
Definition at line 1057 of file server.c.
References config_params::concurrency, LOG, logger(), MAX_CMD_LEN, MAX_COLUMNS_PER_TABLE, MAX_CONNECTIONS, MAX_LISTENQUEUELEN, MAX_RECORDS_PER_TABLE, MAX_TABLES, read_config(), recvline(), config_params::server_host, config_params::server_port, and TableOfData.
bool TestingCharArray (const char * chararray)
Check whether a string is actually a valid integer.
In this function, we handle negative numbers first, then check whether the string is a valid integer or not. If is an integer, return true, otherwise return false
Parameters
chararray The string to be tested
Returns
Return true if it is integer
Definition at line 67 of file server.c.