storage.c File Reference
This file contains the implementation of the storage server interface as specified in storage.h.
#include <stdlib.h>
*
#include <stdio.h>
*
#include <unistd.h>
*
#include <string.h>
*
#include <sys/types.h>
*
#include <sys/socket.h>
*
#include <netdb.h>
*
#include `storage.h`
*
#include `utils.h`
*
#include `logger.h`
*
#include <errno.h>
*
#include <ctype.h>
*
Functions
void ModifyString (char *char_source)
This function is used for removing spaces.
void * storage_connect (const char *hostname, const int port)
This function is for connecting to the server from client side.
int storage_auth (const char *username, const char *passwd, void *conn)
This function is for authentication based on teh username and password inputted by the user.
int storage_get (const char *table, const char *key, struct storage_record *record, void *conn)
This function is for users get the value from the storage server.
int storage_set (const char *table, const char *key, struct storage_record *record, void *conn)
This function is for users set the value inside the storage server.
int storage_disconnect (void *conn)
This function is for disconnecting from the server.
int storage_query (const char *table, const char *predicates, char **keys, const int max_keys, void *conn)
This function is for querying databse for keys that fit.
Variables
int Connected = 0
This is just a minimal stub implementation. You should modify it according to your design.
int Authenticated = 0
Initializing the Authentication for indicating authenticate status, which will be used in the functions below.
FILE * file
Initializing a filestream.
Detailed Description
This file contains the implementation of the storage server interface as specified in storage.h. This storage.c file is used by the client side, which includes several different functions. These functions have the following purposes, which include connect, authenticate, get, set and disconnect
Definition in file storage.c.
Function Documentation
void ModifyString (char * char_source)
This function is used for removing spaces.
When a string be passed inside this function (use pass by parameter, the spaces inside this string will be get ridded.
Parameters
char_source The string which contain spaces and waiting to be purified
Definition at line 54 of file storage.c.
Referenced by storage_query().
int storage_auth (const char * username, const char * passwd, void * conn)
This function is for authentication based on teh username and password inputted by the user.
Authenticate the client's connection to the server.
Parameters
Username The username inputted by the user Passwd The password inputted by the user This is a void pointer for connection purpose
Returns
Return 0 if successful, otherwise return -1
Definition at line 131 of file storage.c.
References Authenticated, ERR_AUTHENTICATION_FAILED, ERR_INVALID_PARAM, file, generate_encrypted_password(), LOG, logger(), MAX_CMD_LEN, recvline(), and sendall().
Referenced by main().
void* storage_connect (const char * hostname, const int port)
This function is for connecting to the server from client side.
Establish a connection to the server.
Parameters
hostname The hostname inputted by the user
port The port inputted by the user
Definition at line 76 of file storage.c.
References Connected, ERR_CONNECTION_FAIL, ERR_INVALID_PARAM, and MAX_PORT_LEN.
Referenced by main().
int storage_disconnect (void * conn)
This function is for disconnecting from the server.
Close the connection to the server.
Parameters
conn This is a void pointer for connection purpose
Definition at line 488 of file storage.c.
References Authenticated, ERR_INVALID_PARAM, file, LOG, and logger().
Referenced by main().
int storage_get (const char * table, const char * key, struct storage_record * record, void * conn)
This function is for users get the value from the storage server.
Retrieve the value associated with a key in a table.
Parameters
table The name of the table
key The name of the key
record Containing the current record
conn This is a void pointer for connection purpose
Returns
Return 0 if successful, otherwise return -1
Definition at line 198 of file storage.c.
References Authenticated, ERR_INVALID_PARAM, ERR_KEY_NOT_FOUND, ERR_NOT_AUTHENTICATED, ERR_TABLE_NOT_FOUND, ERR_UNKNOWN, file, LOG, logger(), MAX_CMD_LEN, storage_record::metadata, recvline(), sendall(), and storage_record::value.
Referenced by main().
int storage_query (const char * table, const char * predicates, char ** keys, const int max_keys, void * conn)
This function is for querying databse for keys that fit.
Query the table for records, and retrieve the matching keys.
With the help of this function, the program can get the required data from the server, based on the predicates inputted by the user.
Parameters
table The table of records array
predicates The conditions given by the user
keys An array which makes strings as its elements, and used to match the predicates
max_keys The number of elements inside the array of string `keys`
Returns
If the function be executed successfully, the number of the matching elements is returned. Otherwise, a value of -1 is returned.
Definition at line 536 of file storage.c.
References Authenticated, ERR_INVALID_PARAM, ERR_NOT_AUTHENTICATED, ERR_TABLE_NOT_FOUND, ERR_UNKNOWN, file, LOG, logger(), MAX_CMD_LEN, MAX_STRTYPE_SIZE, ModifyString(), ModifyString2(), recvline(), and sendall().
Referenced by main().
int storage_set (const char * table, const char * key, struct storage_record * record, void * conn)
This function is for users set the value inside the storage server.
Store a key/value pair in a table.
Parameters
table The name of the table
key The name of the key
record The current record in struct storage_record type
conn This is a void pointer for connection purpose
Definition at line 348 of file storage.c.
References Authenticated, ERR_INVALID_PARAM, ERR_NOT_AUTHENTICATED, ERR_TABLE_NOT_FOUND, ERR_TRANSACTION_ABORT, ERR_UNKNOWN, file, LOG, logger(), MAX_CMD_LEN, storage_record::metadata, recvline(), sendall(), and storage_record::value.
Referenced by main().
Variable Documentation
FILE* file
Initializing a filestream.
Building a filestream named file.
Definition at line 41 of file storage.c.
Referenced by main(), read_config(), storage_auth(), storage_disconnect(), storage_get(), storage_query(), and storage_set().