utils.c File Reference
This file implements various utility functions that are can be used by the storage server and client library.
#include <stdlib.h>
*
#include <stdio.h>
*
#include <string.h>
*
#include <sys/types.h>
*
#include <sys/socket.h>
*
#include <unistd.h>
*
#include <stdbool.h>
*
#include `utils.h`
*
Functions
void ModifyString2 (char *char_source)
This function is used for removing spaces.
int TestingStringCorrectness (char *char_array_tested)
This function is used for testing the validity of the line.
int sendall (const int sock, const char *buf, const size_t len)
This function is used for sending data through the socket.
int recvline (const int sock, char *buf, const size_t buflen)
Receive an entire line from a socket.
int process_config_line (char *line, struct config_params *params)
Parse and process a line in the config file.
int read_config (const char *config_file, struct config_params *params)
Read and load configuration parameters.
void logger (FILE *file, char *message)
Generates a log message.
char * generate_encrypted_password (const char *passwd, const char *salt)
Generates an encrypted password string using salt CRYPT_SALT.
Detailed Description
This file implements various utility functions that are can be used by the storage server and client library. Most of the functions in this file have different utilities, while can be used by server side or client side in order to connect with each other, send data, read configuration file, process configuration file and generate encrypted password for security purpose
Definition in file utils.c.
Function Documentation
char* generate_encrypted_password (const char * passwd, const char * salt)
Generates an encrypted password string using salt CRYPT_SALT.
Parameters
passwd Password before encryption.
salt Salt used to encrypt the password. If NULL default value DEFAULT_CRYPT_SALT is used.
Returns
Returns encrypted password.
Definition at line 627 of file utils.c.
References DEFAULT_CRYPT_SALT.
Referenced by main(), and storage_auth().
void logger (FILE * file, char * message)
Generates a log message.
Parameters
file The output stream
message Message to log.
Definition at line 611 of file utils.c.
Referenced by main(), storage_auth(), storage_disconnect(), storage_get(), storage_query(), and storage_set().
void ModifyString2 (char * char_source)
This function is used for removing spaces.
When a string be passed inside this function (pass by parameter), the spaces inside this string will be get removed.
Parameters
char_source The string which contain spaces about to be removed
Definition at line 34 of file utils.c.
Referenced by process_config_line(), and storage_query().
int process_config_line (char * line, struct config_params * params)
Parse and process a line in the config file.
Parameters
line Containing a line of strings
params Containing the data taken from configuration file
char ColumnNameArray[MAX_COLNAME_LEN*MAX_COLUMNS_PER_TABLE]; ///For storing each column name inside char ColumnTypeArray[MAX_COLNAME_LEN*MAX_COLUMNS_PER_TABLE]; ///For storing each column type inside
printf(`column2: %s \n\n`, token2);
Definition at line 141 of file utils.c.
References config_params::concurrency, MAX_COLNAME_LEN, MAX_COLUMNS_PER_TABLE, MAX_CONFIG_LINE_LEN, MAX_STRTYPE_SIZE, MAX_TABLES, ModifyString2(), config_params::password, config_params::server_host, config_params::server_port, TestingStringCorrectness(), and config_params::username.
Referenced by read_config().
int read_config (const char * config_file, struct config_params * params)
Read and load configuration parameters.
Parameters
config_file The name of the configuration file.
params The structure where config parameters are loaded.
Returns
Return 0 on success, -1 otherwise.
Definition at line 558 of file utils.c.
References file, MAX_CONFIG_LINE_LEN, config_params::password, process_config_line(), config_params::server_host, config_params::server_port, and config_params::username.
Referenced by main().
int recvline (const int sock, char * buf, const size_t buflen)
Receive an entire line from a socket.
Returns
Return 0 on success, -1 otherwise
Parameters
sock The socket which will be used
buf A buffer for storing string inside
buflen The length of the buffer
Definition at line 106 of file utils.c.
Referenced by main(), storage_auth(), storage_get(), storage_query(), and storage_set().
int sendall (const int sock, const char * buf, const size_t len)
This function is used for sending data through the socket.
Keep sending the contents of the buffer until complete.
Parameters
sock The socket number
buf The buf for characters
len The length of the characters with type const size_t
Definition at line 80 of file utils.c.
Referenced by storage_auth(), storage_get(), storage_query(), and storage_set().
int TestingStringCorrectness (char * char_array_tested)
This function is used for testing the validity of the line.
This function is used for testing whether a string has a right format
Parameters
char_array_tested The string to be tested
Definition at line 57 of file utils.c.
Referenced by process_config_line().